version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: server/server-nginx.docker
        image: drupal-web-nginx-1.10
        volumes_from:
            - app
        ports:
            - "8085:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: php/app-php-5.6.docker
        image: drupal-php-5.6
        volumes:
            - ./code:/var/www
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=drupal"
        ports:
            - "33065:3306"